config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:create, :destroy]
  get '/sessions/new', to: 'sessions#new', as: '/login'
  resources :socializations
  resources :learnings
  resources :hobbies
  resources :jobs
  resources :users do 
    resources :children do
      resources :main_children, only: [:show, :new, :destroy]
      post '/user/:user_id/children/:child_id' => 'main_children#create', as: :new_main_child
      resources :personalities #breaking the rule of thumb!
    end
  end
  patch '/users/:user_id/children/:id/independence' => 'children#independence', as: :independence
  root to: 'sessions#root', as: :home
end

app/controllers/children_controller.rb
require 'pry'
class ChildrenController < ApplicationController
    before_action :require_login

    def index
        @children = Child.all.find_by(user_id:params[:user_id])
    end

    def new
        @child = Child.new
    end

    def create

        @child = Child.new(child_params(:first_name, :last_name, :user_id))
        @child.base
        if @child.save
            @child.c_personality
            if @child.personality_id
                # binding.pry
                redirect_to user_child_path(@current_user, @child)
            else
                @child.destroy
                render :new
            end
        else
            render :new
        end
    end

    def show

        @child = Child.find(params[:id])
        render :layout => 'child' 
    end

    def edit

        @child = Child.find(params[:id])
        render :layout => 'child_edit' 
    end

    def update 

        @child = Child.find(params[:id])
        @child.action(params)
        @child.aging(@child)
        @child.save
        redirect_to user_child_path(@current_user, @child)
    end 

    def destroy
        @child = Child.find(params[:id])
        @temp_name = @child.full_name
        @child.destroy!
        redirect_to user_children_path, :notice => "#{@temp_name} is not your child anymore."
    end

    def independence

        @child = Child.find(params[:id])
        @child.job_id = @child.temp_job_id
        @child.save
        redirect_to user_child_path(@current_user, @child)
    end

private

    def child_params(*args)
        params.permit(*args)
    end

end

app/views/children/edit.html.erb
<h2> <%= @child.full_name %> </h2>
<b> Age: <%= @child.age_i %><br>
 Season: <%= @child.season %> </b>
 <br> <br><br><br>
 <% if @child.not_yet? %>
    Your child has a job offer! <br>
    <b> <%= @child.c_job %> </b><br><br>
    You can take the job and give indepence or continue onto more studying!<br>
    <%= link_to "Take the job!", independence_path, method: :patch %><br>
<% elsif @child.job_id == 3 && @child.age == 23.00 %> 
    Your child decided that <%= @child.he_she %> is old enough to be independent! <br>
    <%= @child.he_she %> decided to be: <%= @child.c_job %> <br>
    <%= link_to "Say farewell!", independence_path, method: :patch %><br>
<% end %>
<br><br>
<div>
<% if @child.no_more? %>
    <%= form_tag(user_child_path, method: "patch") do |f| =%>
        <% grouped_options = {learning:[], hobby:[], socialization:[]} %>
        <% Learning.all.each do |act| %>
            <% grouped_options[:learning] << [act.action, ["Learning", act.id]] %>
        <% end %>
        <% Hobby.all.each do |act| %>
            <% grouped_options[:hobby] << [act.action, ["Hobby", act.id]] %>
        <% end %>
        <% Socialization.all.each do |act| %>
            <% grouped_options[:socialization] << [act.action, ["Socialization", act.id]] %>
        <% end %>
        <div class="schedule">
        9 AM ~ 10 AM : 
        <%= select_tag :activity1, grouped_options_for_select(grouped_options), :class=>"select-css" %><br><br>
        10 AM ~ 11 PM :
        <%= select_tag :activity2, grouped_options_for_select(grouped_options), :class=>"select-css" %><br><br>
        11 AM ~ 12 PM :
        <%= select_tag :activity3, grouped_options_for_select(grouped_options), :class=>"select-css" %><br><br>
        1 PM ~ 2 PM :
        <%= select_tag :activity4, grouped_options_for_select(grouped_options), :class=>"select-css" %><br><br>
        2 PM ~ 3 PM :
        <%= select_tag :activity5, grouped_options_for_select(grouped_options), :class=>"select-css" %><br><br>
        3 PM ~ 4 PM
        <%= select_tag :activity6, grouped_options_for_select(grouped_options), :class=>"select-css" %><br><br>
        <%= submit_tag "Schedule set for #{@child.season}" %>
        </div>
    <% end %>
<% end %>
</div>
<br><br>

app/views/children/index.html.erb
<h2> All Children's Contact </h2> 
Adoption maximum is 20! <br><br>

<% if params[:notice] %>
    <%= params[:notice] %>
<% end %>

<ul>
<% if @current_user.children.size > 0 %>
    <% @current_user.children.each do |child| %>
        <li>
        <b><%= link_to child.full_name, user_child_path(@current_user, child) %></b>
        </li>
        Age: <%= child.age_i %>  <br>
        Season: <%= child.season %><br><br>
    <% end %>
<% else %>
        <label>You currently have no adopted children.</label>
<% end %>
</ul>

app/views/children/new.html.erb
<b>
<% if @child.errors.any? %>
    <% @child.errors.full_messages.each do |msg| %>
        <%= msg %> <br>
    <% end %>
<% end %>
</b>

<h2> Adopt to Your Child! </h2>

<%= form_tag user_children_path do %>
    <label> First Name: </label>
    <%= text_field_tag :first_name %><br>
    <label> Last Name: </label>
    <%= text_field_tag :last_name %><br>
       <br>    

<%= submit_tag "Adopt A Child" %>
<% end %>
    <br>

app/views/children/post_update.html.erb
<h2> <%= @child.full_name %> </h2>
<b> Age: <%= @child.age %>  Season: <%= @child.season %> </b>


<ul>
Age: <%= @child.age_i %>
Season: <%= @child.season %>
Gender: <%= @child.gender %>

Happiness: <%= @child.happiness %>
Ambition: <%= @child.ambition %>

Language: <%= @child.language %>
Mathematic: <%= @child.mathematic %>
Coding: <%= @child.coding %>
Art: <%= @child.art %>

Job: <%= @child.job.title %>
</ul>


<%= link_to "Assign schedule", edit_child_path(child) %>

app/views/children/show.html.erb
<h2> <%= @child.first_name + "'s" + " Current Status" %> </h2>

<b> Season: <%= @child.season %><br> </b>
<ul>

Age: <%= @child.age_i %><br>
<br>
Gender: <%= @child.gender %><br>
<br>
Happiness: <%= number_with_precision(@child.happiness, precision: 2)  %><br>
Ambition: <%= number_with_precision(@child.ambition, precision: 2) %><br>
<br>
Language: <%= number_with_precision(@child.language, precision: 2) %><br>
Mathematic: <%= number_with_precision(@child.mathematic, precision: 2) %><br>
Coding: <%= number_with_precision(@child.coding, precision: 2) %><br>
Art: <%= number_with_precision(@child.art, precision: 2) %><br>
<br>
Job: <%= @child.job.title %><br><br>
</ul>


<br><br>