config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:create, :destroy]
  get '/sessions/new', to: 'sessions#new', as: '/login'
  resources :socializations
  resources :learnings
  resources :hobbies
  resources :jobs
  resources :users do 
    resources :children do
      resources :main_children, only: [:show, :new, :destroy]
      post '/user/:user_id/children/:child_id' => 'main_children#create', as: :new_main_child
      resources :personalities #breaking the rule of thumb!
    end
  end
  patch '/users/:user_id/children/:id/independence' => 'children#independence', as: :independence
  root to: 'sessions#root', as: :home
end

app/models/user.rb
class User < ApplicationRecord
    has_many :children, :dependent => :destroy
    has_many :main_children, :dependent => :destroy
    
    has_secure_password
    validates :username, presence: true, uniqueness: true, length: { in: 4..20 }

    def max_number
        all = []
        if Child.where(user_id:self.id).count <= 20
            return true
        else
            return false
        end
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: [:index, :new, :create]

    def index
        @users = User.all
        render :layout => 'no_login'    
    end

    def show
        @my_children = []
        Child.all.each do |child|
           if child.user_id == @current_user.id
                @my_children << child
           end
        end
        @main_children = []
        MainChild.all.each do |child|
           if child.user_id == @current_user.id
                @main_children << child
           end
        end
    end

    def new
        @user = User.new
        if session[:user_id] != nil 
        else
            render :layout => 'no_login'
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:username] = @user[:username]
            redirect_to login_path
        else 
            render :new
        end
    end

private

    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end

end

app/views/users/index.html.erb
<h2> All Users and Their Main Children </h2>

<% @users.each do |user| %>
    <b><%= user.username %></b>
    <ul>
    <% if MainChild.find_by(user_id:user.id) %>
        <% @main_children = [] %>
        <% MainChild.all.each do |child| %>
            <% if child.user_id == user.id %>
                <% @main_children << child %>
            <% end %>
        <% end %>
        <% @main_children.each do |mchild| %>
            <li> 
            <% child = Child.find(mchild.child_id) %>
            <%= link_to child.full_name, user_child_main_child_path(child_id:child.id, id:mchild.id, user_id:user.id) %><br>  
            </li>
            </t>Job: <%= child.job.title %>
        <% end %>
    <% else %>
        This user has not setup main child yet.
    <% end %>
    </ul>
<% end %>

<br><br>

app/views/users/new.html.erb
<h2> Create New User </h2>

<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
        <%= msg %>
    <% end %>
<% end %>

Username must be unique.
Password must be between 4 to 20 characters.
<br><br>
<%= form_for @user do |f| %>
    <label><b> Username: </label>
    <%= f.text_field :username %><br>
    <label> Password: </label>
    <%= f.text_field :password %><br>
    <label> Password confirmation: </label>
    <%= f.text_field :password, confirmation: true %><br> </b><br><br>
    <%= f.submit "Become a New Parent" %>
<% end %>
<br><br>

app/views/users/show.html.erb
<h2> My Main Children </h2>
Main children will be visible to other users.<br><br>

<% if @main_children.size > 0 %>
    <ul>
    <% @main_children.each do |m_child| %>
        <li>
        <% child = Child.find(m_child.child_id) %>
        <%= link_to child.full_name, user_child_path(child.id) %> 
        </li>
    <% end %>
    </ul>
<% else %>
    There is no main child to share with other parents.
<% end %>
<br><br>
<h2> My Independent Children </h2>
<% if @my_children.size > 0 %>
<% i_child = [] %>
    <% @my_children.each do |child| %>
        <% if child.job_id != 1 && child.job_id != 3 %>
            <% i_child << child %>
        <ul>
            <li>
            <%= link_to child.full_name, user_child_path(child.id) %><br>
            </li>
    Age:    <%= child.age_i %><br>
    Career: <%= Job.find(child.job_id).title %><br><br>
        <ul>
        <% end %>
    <% end %>
    <% if i_child.length == 0 %>
        There is no child at this time.
    <% end %>
<% else %>
There is no child at this time.
<% end %>
<br>
<br>
<br>